### ISSUE TITLE
Content-component as extensible area - Auxiliary and main content

### ISSUE THREAD

**Issue by GuiLeme** [bigbluebutton/bigbluebutton-html-plugin-sdk#76]
### Context
After some discussion, and requests to add the side-bar pannel as a possible extensible-area to play around, we came to the conclusion that a good way to make it happen is to add it as a type of the generic-component extensible-area, but with that, it would be necessary to refactor the generic-component and even rename it.

### Suggestions:
Maybe we could rename the generic component to content-component and allow the user to specify its type, which they could choose between:
- main-content;
- auxiliary-content;

Just as we already do with `ActionButtonDropdown(Separator or Option)`.

As for the `auxiliary-content` type, it would be rendered within the user-list pannel (the one in the far left edge of the UI) as a clickable option like the shared-notes button, which will render the content right beside it as the chat does or the shared-notes even. See screenshots ahead for better understanding:

![image](https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/assets/69865537/569ea4a5-22ee-4072-9a41-3cbd726c4e04)

The red-squared area is what I refer to as "user-list pannel", and the arrow points to where we could add another option for when the user clicks it, the auxiliary-content renders right beside it.

So on that regards, we are open for suggestions as we can improve the UI and the developer's experience even better. Just comment what you think of, and let's discuss!

**Comment by gustavotrott** [comment]
I don't know why, but I didn't like the name "auxiliary-content".

What about "Sidekick Panel"?

**Comment by TiagoJacobs** [comment]
Having "side" in the name was not our first choice, because we can decide to show it on another place in screen.

The word sidekick helps in this matter, however, calling it as panel is not good, because panel is where it's displayed, in the plugin we define what is being displayed.

So I think we could have:
- main content
- sidekick content

And these would be rendered into:
- main panel
- sidekick panel

Does it make sense?

**Comment by gustavotrott** [comment]
> Having "side" in the name was not our first choice, because we can decide to show it on another place in screen.
> 
> 
> 
> The word sidekick helps in this matter, however, calling it as panel is not good, because panel is where it's displayed, in the plugin we define what is being displayed.
> 
> 
> 
> So I think we could have:
> 
> - main content
> 
> - sidekick content
> 
> 
> 
> And these would be rendered into:
> 
> - main panel
> 
> - sidekick panel
> 
> 
> 
> Does it make sense?
> 
> 

sounds good!
